// This test suite was predominantly generated by Claude Sonnet 4.6.

import { describe, expect, it } from "vitest";
import {
	type BinaryNode,
	type Node,
	type ValueNode,
	type MealItem,
	type MealRecord,
	evaluateMealItem,
	evaluateMealRecord,
	// parseJoule
} from "../lib/types";
import { O } from "../lib";
// import { DEFAULT_SETTINGS } from "../settings.ts";
import { parseJoule } from "../lib/parser.ts";

const units = ["g", "ml", "cup", "cups", "cnt", "count"];

function assert<T>(val: T) {
	expect(val).toBeTruthy();
}

function assertAlmostEquals<T extends number>(valA: T, valB: T) {
	expect(valA).toBeCloseTo(valB);
}

function assertEquals<T>(valA: T, valB: T) {
	expect(valA).toEqual(valB);
}

function assertExists<T>(val: T) {
	expect(val).toBeDefined();
	expect(val).not.toBeNull();
}

function assertOk<T>(result: O.Result<T>): asserts result is O.Ok<T> {
	expect(result._tag).toBe("ok");
}

// ---------------------------------------------------------------------------
// Node-building helpers
//
// The parser stores formulas as an AST (Node), not as strings.
// These factories mirror the shapes produced by parseMealRecord so that
// evaluation tests can construct MealItem objects without going through
// the parser.
// ---------------------------------------------------------------------------

const num = (value: number): ValueNode => ({ value, kind: "value" });
const s = (): ValueNode => ({ value: "s", kind: "value" });
const binop = (
	op: BinaryNode["op"],
	left: Node,
	right: Node,
): BinaryNode => ({ op, left, right, kind: "binary" });

// ---------------------------------------------------------------------------
// Source helpers
// ---------------------------------------------------------------------------

/**
 * Wraps raw joule text in a fenced Markdown code block.
 * NOTE: the item parser requires the formula to be parenthesised:
 *   <quantity> [unit] <name> (<formula>)
 */
const jouleBlock = (inner: string) => `\`\`\`joule\n${inner}\n\`\`\``;

// ---------------------------------------------------------------------------
// 1. PARSING — valid inputs
// ---------------------------------------------------------------------------

describe("parseJoule – valid inputs", () => {
	it("returns an array containing one MealRecord per joule block", () => {
		const src = jouleBlock("Breakfast\n1 Egg (s*70)");
		const result = parseJoule(src, units);
		assertOk(result);

		assertEquals(result.value.length, 1);
		assertExists(result.value[0]);
	});

	it("parses the meal name correctly", () => {
		const src = jouleBlock("Breakfast\n1 Egg (s*70)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;

		assertEquals(meal.name, "Breakfast");
	});

	it("parses a single item — quantity, name, and formula node present", () => {
		const src = jouleBlock("Breakfast\n1 Egg (s*70)");
		const result = parseJoule(src, units);
		assertOk(result);

		const meal = result.value[0]!;

		assertEquals(meal.items.length, 1);
		const item = meal.items[0]!;
		assertEquals(item.quantity, 1);
		assertEquals(item.name, "Egg");
		// formula is an AST node, not a string
		assertExists(item.formula);
	});

	it("parses the formula AST for a simple multiplication (s*70)", () => {
		const src = jouleBlock("Breakfast\n1 Egg (s*70)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		// s*70  →  { op:"*", left:{value:"s"}, right:{value:70} }
		assertEquals(item.formula, binop("*", s(), num(70)));
	});

	it("parses the formula AST for a constant (500)", () => {
		const src = jouleBlock("Test\n1 Constant (500)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertEquals(item.formula, num(500));
	});

	it("parses the formula AST for addition (s+100)", () => {
		const src = jouleBlock("Test\n50 Mix (s+100)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		// s+100  →  { op:"+", left:{value:"s"}, right:{value:100} }
		assertEquals(item.formula, binop("+", s(), num(100)));
	});

	it("parses the formula AST for subtraction (s-30)", () => {
		const src = jouleBlock("Test\n80 Item (s-30)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertEquals(item.formula, binop("-", s(), num(30)));
	});

	it("parses the formula AST for division (s/2)", () => {
		const src = jouleBlock("Test\n200 Milk (s/2)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertEquals(item.formula, binop("/", s(), num(2)));
	});

	it("parses an item with an explicit unit", () => {
		const src = jouleBlock("Lunch\n200 g Chicken Breast (2*s)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertEquals(item.quantity, 200);
		assertEquals(item.unit, "g");
		assertEquals(item.name, "Chicken Breast");
	});

	it("parses an item without a unit (unit field is undefined)", () => {
		const src = jouleBlock("Breakfast\n1 Egg (s*70)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertEquals(item.unit, undefined);
	});

	it("parses a floating-point quantity", () => {
		const src = jouleBlock("Snack\n1.5 cups Oats (s*350)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertAlmostEquals(item.quantity, 1.5);
		assertEquals(item.name, "Oats");
	});

	it("parses a zero quantity", () => {
		const src = jouleBlock("Test\n0 g Sugar (s*4)");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		const item = meal.items[0]!;

		assertEquals(item.quantity, 0);
	});

	it("parses multiple items in one meal", () => {
		const src = jouleBlock(
			"Dinner\n150 g Salmon (s*2)\n100 g Rice (s*1.3)\n200 ml Milk (s*0.42)",
		);
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;

		assertEquals(meal.name, "Dinner");
		assertEquals(meal.items.length, 3);
		assertEquals(meal.items[0]!.name, "Salmon");
		assertEquals(meal.items[1]!.name, "Rice");
		assertEquals(meal.items[2]!.name, "Milk");
	});

	it("parses a meal with no items", () => {
		const src = jouleBlock("WaterFast");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;

		assertEquals(meal.name, "WaterFast");
		assertEquals(meal.items, []);
	});

	it("returns an empty array when there are no joule blocks", () => {
		// Non-joule fences are silently ignored — no throw
		const src = "```python\nBreakfast\n1 Egg (s*70)\n```";
		const result = parseJoule(src, units);
		assertOk(result);

		assertEquals(result.value, []);
	});

	it("returns an empty array when there are no fenced blocks at all", () => {
		const result = parseJoule("Breakfast\n1 Egg (s*70)", units);
		assertOk(result);

		assertEquals(result.value, []);
	});

	it("returns multiple records for multiple joule blocks", () => {
		const src = jouleBlock("Breakfast\n1 Egg (s*70)") +
			"\n\n" +
			jouleBlock("Lunch\n200 g Chicken (2*s)");
		const result = parseJoule(src, units);
		assertOk(result);

		assertEquals(result.value.length, 2);
		assertEquals(result.value[0]!.name, "Breakfast");
		assertEquals(result.value[1]!.name, "Lunch");
	});
});

// ---------------------------------------------------------------------------
// 2. PARSING — invalid joule block contents
// ---------------------------------------------------------------------------

describe("parseJoule – invalid joule block contents", () => {
	it("fails when a joule block is completely empty", () => {
		const result = parseJoule(jouleBlock(""), units);
		expect(result._tag).not.toBe("ok");
	});

	it("fails when an item line has no formula parentheses", () => {
		// Formula is mandatory and must be parenthesised
		const result = parseJoule(jouleBlock("Lunch\n100 g Chicken"), units);
		expect(result._tag).not.toBe("ok");
	});

	it("fails when a formula is present but not wrapped in parentheses", () => {
		const result = parseJoule(
			jouleBlock("Lunch\n100 g Chicken s*2"),
			units,
		);
		expect(result._tag).not.toBe("ok");
	});

	it("fails when quantity is not a number", () => {
		const result = parseJoule(
			jouleBlock("Breakfast\nabc g Oats (s*350)"),
			units,
		);
		expect(result._tag).not.toBe("ok");
	});
});

// ---------------------------------------------------------------------------
// 3. EVALUATION — MealItem
//
// evaluateMealItem(item) substitutes s = item.quantity into the formula AST
// and returns the resulting caloric value.
//
// Items are constructed directly using Node literals to be independent of
// the parser.
// ---------------------------------------------------------------------------

describe("evaluateMealItem", () => {
	it("evaluates a constant formula (no s)", () => {
		const item: MealItem = {
			quantity: 1,
			name: "Egg",
			formula: num(70),
		};
		assertAlmostEquals(evaluateMealItem(item), 70);
	});

	it("evaluates s*k — substitutes quantity for s", () => {
		// s=100, formula: s*2  →  200
		const item: MealItem = {
			quantity: 100,
			name: "Chicken",
			formula: binop("*", s(), num(2)),
		};
		assertAlmostEquals(evaluateMealItem(item), 200);
	});

	it("evaluates k*s — multiplication is commutative", () => {
		// s=100, formula: 2*s  →  200
		const item: MealItem = {
			quantity: 100,
			name: "Chicken",
			formula: binop("*", num(2), s()),
		};
		assertAlmostEquals(evaluateMealItem(item), 200);
	});

	it("evaluates s+k", () => {
		// s=50, formula: s+100  →  150
		const item: MealItem = {
			quantity: 50,
			name: "Mix",
			formula: binop("+", s(), num(100)),
		};
		assertAlmostEquals(evaluateMealItem(item), 150);
	});

	it("evaluates s-k", () => {
		// s=80, formula: s-30  →  50
		const item: MealItem = {
			quantity: 80,
			name: "Item",
			formula: binop("-", s(), num(30)),
		};
		assertAlmostEquals(evaluateMealItem(item), 50);
	});

	it("evaluates s/k", () => {
		// s=200, formula: s/2  →  100
		const item: MealItem = {
			quantity: 200,
			name: "Milk",
			formula: binop("/", s(), num(2)),
		};
		assertAlmostEquals(evaluateMealItem(item), 100);
	});

	it("evaluates a nested formula: (s+5)*3", () => {
		// s=10, formula: (s+5)*3  →  45
		const item: MealItem = {
			quantity: 10,
			name: "Item",
			formula: binop("*", binop("+", s(), num(5)), num(3)),
		};
		assertAlmostEquals(evaluateMealItem(item), 45);
	});

	it("evaluates correctly when quantity is zero", () => {
		// s=0, formula: s*4  →  0
		const item: MealItem = {
			quantity: 0,
			name: "Sugar",
			formula: binop("*", s(), num(4)),
		};
		assertAlmostEquals(evaluateMealItem(item), 0);
	});

	it("evaluates correctly with a floating-point quantity", () => {
		// s=1.5, formula: s*350  →  525
		const item: MealItem = {
			quantity: 1.5,
			name: "Oats",
			formula: binop("*", s(), num(350)),
		};
		assertAlmostEquals(evaluateMealItem(item), 525);
	});

	it("returns a non-finite value on division by zero", () => {
		// s=5, formula: s/0
		const item: MealItem = {
			quantity: 5,
			name: "Item",
			formula: binop("/", s(), num(0)),
		};
		const result = evaluateMealItem(item);
		assert(!isFinite(result) || isNaN(result));
	});
});

// ---------------------------------------------------------------------------
// 4. EVALUATION — MealRecord (total calories)
// ---------------------------------------------------------------------------

describe("evaluateMealRecord", () => {
	it("returns 0 for a meal with no items", () => {
		const record: MealRecord = { name: "FastingDay", items: [] };
		assertEquals(evaluateMealRecord(record), 0);
	});

	it("returns the item's value when there is only one item", () => {
		const record: MealRecord = {
			name: "Snack",
			items: [{ quantity: 1, name: "Apple", formula: num(52) }],
		};
		assertAlmostEquals(evaluateMealRecord(record), 52);
	});

	it("sums the caloric values of all items", () => {
		const record: MealRecord = {
			name: "Breakfast",
			items: [
				{
					quantity: 2,
					name: "Eggs",
					formula: binop("*", s(), num(70)),
				}, // 140
				{
					quantity: 30,
					name: "Oats",
					formula: binop("*", s(), num(3.5)),
				}, // 105
			],
		};
		assertAlmostEquals(evaluateMealRecord(record), 245);
	});

	it("items with zero quantity contribute 0 to the total", () => {
		const record: MealRecord = {
			name: "Test",
			items: [
				{
					quantity: 0,
					name: "Sugar",
					formula: binop("*", s(), num(4)),
				}, // 0
				{
					quantity: 100,
					name: "Rice",
					formula: binop("*", s(), num(1.3)),
				}, // 130
			],
		};
		assertAlmostEquals(evaluateMealRecord(record), 130);
	});

	it("total equals the sum of individual evaluateMealItem calls", () => {
		const record: MealRecord = {
			name: "Dinner",
			items: [
				{
					quantity: 150,
					name: "Salmon",
					formula: binop("*", s(), num(2.08)),
				},
				{
					quantity: 100,
					name: "Broccoli",
					formula: binop("*", s(), num(0.34)),
				},
				{
					quantity: 200,
					name: "Milk",
					formula: binop("*", s(), num(0.42)),
				},
			],
		};
		const expected = record.items.reduce(
			(sum, item) => sum + evaluateMealItem(item),
			0,
		);
		assertAlmostEquals(evaluateMealRecord(record), expected);
	});
});

// ---------------------------------------------------------------------------
// 5. ROUND-TRIP — parse then evaluate
// ---------------------------------------------------------------------------

describe("round-trip: parse -> evaluate", () => {
	it("parses and evaluates a realistic breakfast", () => {
		const src = jouleBlock(
			"Breakfast\n2 large Eggs (s*70)\n30 g Oats (s*3.5)\n200 ml Milk (s*0.42)",
		);
		// 2*70 + 30*3.5 + 200*0.42 = 140 + 105 + 84 = 329
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		assertExists(meal);
		assertAlmostEquals(evaluateMealRecord(meal), 329);
	});

	it("parses and evaluates a single-item meal", () => {
		// s=25, formula: (s*4+10)  →  110
		// Note: due to the parser's precedence rules (mul joins add sub-expressions),
		// this formula must be written as nested groups to guarantee the intended
		// evaluation order: (s*4)+10 should be written as two explicit groups.
		const src = jouleBlock("Protein Shake\n25 g Whey (s*4)");
		// 25 * 4 = 100
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		assertExists(meal);
		assertAlmostEquals(evaluateMealRecord(meal), 100);
	});

	it("a zero-item meal evaluates to 0 after parsing", () => {
		const src = jouleBlock("WaterFast");
		const result = parseJoule(src, units);
		assertOk(result);
		const meal = result.value[0]!;
		assertExists(meal);
		assertEquals(evaluateMealRecord(meal), 0);
	});
});
