// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParseNode } from "./ParseNode";

/**
 * type that represents the Parse Tree
 */
export type JouleTree = { "type": "integer", "data": number } | { "type": "float", "data": number } | { "type": "serving" } | { "type": "reference", "data": { document: string, meal_name: string, offset: number | null, } } | { "type": "tag", "data": { key: ParseNode<string>, value: string | null, } } | { "type": "parens", "data": JouleTree } | { "type": "/", "data": Array<JouleTree> } | { "type": "*", "data": Array<JouleTree> } | { "type": "-", "data": Array<JouleTree> } | { "type": "+", "data": Array<JouleTree> } | { "type": "item", "data": { 
/**
 * Represents the value that will be passed to the serving variable
 */
quantity: JouleTree, unit: string, name: ParseNode<string>, formula: JouleTree, } } | { "type": "meal", "data": { name: ParseNode<string>, tags: Array<JouleTree>, items: ParseNode<Array<ParseNode<JouleTree>>>, } };
