// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Encapsulates a range-indexed syntax object.
 * This exists to power suggestions; The idea is to fetch the most narrow interval / ParseNode within which the cursor lies.
 */
export type ParseNode<T> = { 
/**
 * Input spanned by [span.0, span.1)
 */
span: [number, number], 
/**
 * Data contained by the node
 */
data: T, };
